### ISSUE TITLE
Source does not compile on Ubuntu 25.10 (Questing Quokka)

### ISSUE THREAD

**Issue by eshoubak** [gridlab-d/gridlab-d#1742]
Following compilation steps, I get the same following error in many places:

```
/root/src/gridlab-d/gldcore/property.h: In member function ‘char* charbuf<size>::token(char*, const char*, char**)’:
/root/src/gridlab-d/gldcore/platform.h:45:26: error: ‘class charbuf<size>’ has no member named ‘strtok_r’ [-Wtemplate-body]
   45 |         #define strtok_s strtok_r
      |                          ^~~~~~~~
```

and compilation fails.

The same steps work fine on ubuntu 24.04 (Noble)

The same issue is encountered when compiling for Tahoe (MacOS)

**Comment by eshoubak** [comment]
Looking at it closely:
ok, the issue seems to be in the `charbuf` class defined in gldcore/property.h, specifically this method:

`inline char *token(char *from, const char *delim, char **context) { return this->strtok_s(from, delim, context); };`

clearly `charbuf` has no method strtok_s. If I remove the "this->" the source compiles fine.

But now I am utterly confused about why this compiles at all in older versions of ubuntu???? Maybe older versions of gcc miss this at compile time ? and newer versions corrected this bug. Seems plausible.

**Comment by temcdrm** [comment]
I see this error compiling the master branch on MacOS Tahoe.  But not on the develop branch.
