### ISSUE TITLE
Metrics collector writer uses strcat calls that may have copy overlaps.

### ISSUE THREAD

**Issue by dchassin** [gridlab-d/gridlab-d#1294]
There are some `strcat` calls in `tape/metrics_collector_writer.cpp` that may have copy overlaps. See https://github.com/gridlab-d/gridlab-d/blob/46541cb8babdd34e371c42467c3830f03f73b96c/tape/metrics_collector_writer.cpp#L58. 

These lines of codes should be replaced with something like

~~~
snprintf(filename_billing_meter,sizeof(filename_billing_meter)-1,"billing_meter_%s",filename);
snprintf(filename_inverter,sizeof(filename_inverter)-1,"inverter_%s",filename);
snprintf(filename_capacitor,sizeof(filename_capacitor)-1,"capacitor_%s",filename);
snprintf(filename_regulator,sizeof(filename_regulator)-1,"regulator_%s",filename);
snprintf(filename_house,sizeof(filename_house)-1,"house_%s",filename);
snprintf(filename_substation,sizeof(filename_substation)-1,"substation_%s",filename);
~~~

It addition, to ensure sufficient space is available for the resulting string, the target strings should all be made `char1024`.

**Comment by d3j331** [comment]
Close issue, with commit b452517

**Comment by trevorhardy** [comment]
Not working on Mac using Clang 12.0.0

```
tape/metrics_collector_writer.cpp:182:104: error: cannot pass non-trivial object of type 'char256' (aka 'charbuf<257>') to variadic function; expected type from format string was 'char *' [-Wnon-pod-varargs]
                snprintf(filename_billing_meter, sizeof(filename_billing_meter)-1, "%s_%s", m_billing_meter.c_str(), filename);
```
